typography_spectrum: 0.22581002721562982
color:
  brandStrength: 0.4168229333590716
  lightness: 0.12987349391914904
  saturation: 0.6266700867563486
  rhythmicContrast: 0.7733620330691338
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
layout_spectrum: 0.9113839506171644
author:
  url: 'http://tomatishellas.org'
  email: akalostypi@gmail.com
  name: Aikaterina's blog
name: aikaterina's blog
title: "Διαδρομές Μάθησης \_Ελλάς"
description: "aikaterina's \_blog"
